/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: honda_data.proto */

#ifndef PROTOBUF_C_honda_5fdata_2eproto__INCLUDED
#define PROTOBUF_C_honda_5fdata_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct MessageHeader MessageHeader;
typedef struct PowertrainData PowertrainData;
typedef struct EngineData EngineData;
typedef struct GasPedal2 GasPedal2;
typedef struct SteeringSensors SteeringSensors;
typedef struct KinematicsAlt KinematicsAlt;
typedef struct VsaStatus VsaStatus;
typedef struct Standstill Standstill;
typedef struct WheelSpeeds WheelSpeeds;
typedef struct VehicleDynamics VehicleDynamics;
typedef struct SteerMotorTorque SteerMotorTorque;
typedef struct EpbStatus EpbStatus;
typedef struct EconStatus EconStatus;
typedef struct RoughWheelSpeed RoughWheelSpeed;
typedef struct ScmButtons ScmButtons;
typedef struct SeatbeltStatus SeatbeltStatus;
typedef struct CarSpeed CarSpeed;
typedef struct ScmFeedback ScmFeedback;
typedef struct StalkStatus StalkStatus;
typedef struct StalkStatus2 StalkStatus2;
typedef struct DoorsStatus DoorsStatus;
typedef struct Odometer Odometer;
typedef struct GearboxCvt GearboxCvt;
typedef struct HudSetting HudSetting;
typedef struct CruiseData CruiseData;
typedef struct EngineData3 EngineData3;
typedef struct DriveModes DriveModes;
typedef struct Gearbox Gearbox;
typedef struct PCMDATA PCMDATA;
typedef struct VSADATA VSADATA;
typedef struct EPSDATA EPSDATA;
typedef struct OTHERDATA OTHERDATA;
typedef struct ALLDATA ALLDATA;
typedef struct CarStatus CarStatus;
typedef struct VehicleDataBatch VehicleDataBatch;
typedef struct CanData CanData;


/* --- enums --- */

/*
 * EPB状态枚举
 */
typedef enum _EPBState {
  EPBSTATE__EPB_STATE_OFF = 0,
  EPBSTATE__EPB_STATE_ENGAGING = 1,
  EPBSTATE__EPB_STATE_DISENGAGING = 2,
  EPBSTATE__EPB_STATE_ON = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(EPBSTATE)
} EPBState;
/*
 * 巡航按钮枚举
 */
typedef enum _CruiseButton {
  CRUISE_BUTTON__CRUISE_BUTTON_NONE = 0,
  CRUISE_BUTTON__CRUISE_BUTTON_MAIN = 1,
  CRUISE_BUTTON__CRUISE_BUTTON_CANCEL = 2,
  CRUISE_BUTTON__CRUISE_BUTTON_DECEL_SET = 3,
  CRUISE_BUTTON__CRUISE_BUTTON_ACCEL_RES = 4,
  CRUISE_BUTTON__CRUISE_BUTTON_TBD_5 = 5,
  CRUISE_BUTTON__CRUISE_BUTTON_TBD_6 = 6,
  CRUISE_BUTTON__CRUISE_BUTTON_TBD_7 = 7
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CRUISE_BUTTON)
} CruiseButton;
/*
 * CMBS按钮枚举
 */
typedef enum _CMBSButton {
  CMBSBUTTON__CMBS_BUTTON_RELEASED = 0,
  CMBSBUTTON__CMBS_BUTTON_PRESSED = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CMBSBUTTON)
} CMBSButton;
/*
 * 档位选择器枚举
 */
typedef enum _GearShifter {
  GEAR_SHIFTER__GEAR_NONE = 0,
  GEAR_SHIFTER__GEAR_P = 1,
  GEAR_SHIFTER__GEAR_R = 2,
  GEAR_SHIFTER__GEAR_N = 4,
  GEAR_SHIFTER__GEAR_D = 8,
  GEAR_SHIFTER__GEAR_S = 16,
  GEAR_SHIFTER__GEAR_L = 32
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEAR_SHIFTER)
} GearShifter;
/*
 * 雨刷状态枚举
 */
typedef enum _WiperStatus {
  WIPER_STATUS__WIPER_OFF = 0,
  WIPER_STATUS__WIPER_LOW = 2,
  WIPER_STATUS__WIPER_HIGH = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(WIPER_STATUS)
} WiperStatus;

/* --- messages --- */

/*
 * 消息头，包含时间戳和CAN ID信息
 */
struct  MessageHeader
{
  ProtobufCMessage base;
  uint32_t can_id;
  /*
   * google.protobuf.Timestamp timestamp = 1;
   */
  /*
   * 时间戳，单位：微秒
   */
  uint64_t timestamp;
};
#define MESSAGE_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&message_header__descriptor) \
, 0, 0 }


/*
 * ID: 380 - POWERTRAIN_DATA 动力总成数据 20Hz
 */
struct  PowertrainData
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 油门踏板 [0|255]
   */
  uint32_t pedal_gas;
  /*
   * 发动机转速 [0|15000] rpm
   */
  uint32_t engine_rpm;
  /*
   * 油门是否被按下
   */
  protobuf_c_boolean gas_pressed;
  /*
   * ACC状态
   */
  protobuf_c_boolean acc_status;
  /*
   * 位37-41 (5 bits)
   */
  uint32_t boh_17c;
  /*
   * 刹车开关
   */
  protobuf_c_boolean brake_switch;
  /*
   * 位47-56 (10 bits)
   */
  uint32_t boh2_17c;
  /*
   * 刹车是否被按下
   */
  protobuf_c_boolean brake_pressed;
  /*
   * 位52-56 (5 bits)
   */
  uint32_t boh3_17c;
};
#define POWERTRAIN_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&powertrain_data__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0, 0, 0, 0 }


/*
 * ID: 344 - ENGINE_DATA 发动机数据 20Hz
 */
struct  EngineData
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 变速箱速度 (kph)
   */
  float xmission_speed;
  /*
   * 发动机转速 [0|15000] rpm
   */
  uint32_t engine_rpm;
  /*
   * 变速箱速度2 (kph)
   */
  float xmission_speed2;
  /*
   * 里程表 (单位: 10米)
   */
  uint32_t odometer;
};
#define ENGINE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&engine_data__descriptor) \
, NULL, 0, 0, 0, 0 }


/*
 * ID: 304 - GAS_PEDAL_2 油门踏板数据2 20Hz
 */
struct  GasPedal2
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 发动机扭矩估计 [-1000|1000] Nm
   */
  int32_t engine_torque_estimate;
  /*
   * 发动机扭矩请求 [-1000|1000] Nm
   */
  int32_t engine_torque_request;
  /*
   * 油门踏板 [0|255]
   */
  uint32_t car_gas;
};
#define GAS_PEDAL2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gas_pedal2__descriptor) \
, NULL, 0, 0, 0 }


/*
 * ID: 330 - STEERING_SENSORS 转向传感器数据 20Hz
 */
struct  SteeringSensors
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 转向角度 [-500|500] deg
   */
  float steer_angle;
  /*
   * 转向角速度 [-3000|3000] deg/s
   */
  float steer_angle_rate;
  /*
   * 转向传感器状态1
   */
  protobuf_c_boolean steer_sensor_status_1;
  /*
   * 转向传感器状态2
   */
  protobuf_c_boolean steer_sensor_status_2;
  /*
   * 转向传感器状态3
   */
  protobuf_c_boolean steer_sensor_status_3;
  /*
   * 转向盘角度 [-500|500] deg
   */
  float steer_wheel_angle;
};
#define STEERING_SENSORS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&steering_sensors__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0 }


/*
 * ID: 148 - KINEMATICS_ALT 运动学数据（替代） 20Hz
 */
struct  KinematicsAlt
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 横向加速度 [-20|20] m/s²
   */
  float lat_accel;
  /*
   * 纵向加速度 [-20|20] m/s²
   */
  float long_accel;
};
#define KINEMATICS_ALT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&kinematics_alt__descriptor) \
, NULL, 0, 0 }


/*
 * ID: 420 - VSA_STATUS 车辆稳定性控制系统状态 10Hz
 */
struct  VsaStatus
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 用户刹车 [0|1000] (单位: 0.015625, 偏移: -1.609375)
   */
  float user_brake;
  /*
   * 电脑刹车
   */
  protobuf_c_boolean computer_braking;
  /*
   * ESP禁用
   */
  protobuf_c_boolean esp_disabled;
  /*
   * 刹车保持相关
   */
  protobuf_c_boolean brake_hold_related;
  /*
   * 刹车保持激活
   */
  protobuf_c_boolean brake_hold_active;
  /*
   * 刹车保持启用
   */
  protobuf_c_boolean brake_hold_enabled;
};
#define VSA_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&vsa_status__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0 }


/*
 * ID: 432 - STANDSTILL 静止状态 10Hz
 */
struct  Standstill
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 受控静止
   */
  protobuf_c_boolean controlled_standstill;
  /*
   * 车轮移动
   */
  protobuf_c_boolean wheels_moving;
  /*
   * 刹车错误1
   */
  protobuf_c_boolean brake_error_1;
  /*
   * 刹车错误2
   */
  protobuf_c_boolean brake_error_2;
};
#define STANDSTILL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&standstill__descriptor) \
, NULL, 0, 0, 0, 0 }


/*
 * ID: 464 - WHEEL_SPEEDS 车轮速度 10Hz
 */
struct  WheelSpeeds
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 左前轮速度 [0|250] kph
   */
  float wheel_speed_fl;
  /*
   * 右前轮速度 [0|250] kph
   */
  float wheel_speed_fr;
  /*
   * 左后轮速度 [0|250] kph
   */
  float wheel_speed_rl;
  /*
   * 右后轮速度 [0|250] kph
   */
  float wheel_speed_rr;
};
#define WHEEL_SPEEDS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&wheel_speeds__descriptor) \
, NULL, 0, 0, 0, 0 }


/*
 * ID: 490 - VEHICLE_DYNAMICS 车辆动力学数据 10Hz
 */
struct  VehicleDynamics
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 横向加速度 [-20|20] m/s²
   */
  float lat_accel;
  /*
   * 纵向加速度 [-20|20] m/s²
   */
  float long_accel;
};
#define VEHICLE_DYNAMICS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&vehicle_dynamics__descriptor) \
, NULL, 0, 0 }


/*
 * ID: 427 - STEER_MOTOR_TORQUE 转向电机扭矩 10Hz
 */
struct  SteerMotorTorque
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 配置有效
   */
  protobuf_c_boolean config_valid;
  /*
   * 电机扭矩 [0|256]
   */
  uint32_t motor_torque;
  /*
   * 输出禁用
   */
  protobuf_c_boolean output_disabled;
};
#define STEER_MOTOR_TORQUE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&steer_motor_torque__descriptor) \
, NULL, 0, 0, 0 }


/*
 * ID: 450 - EPB_STATUS 电子驻车制动状态 10Hz
 */
struct  EpbStatus
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * EPB刹车和拉动
   */
  protobuf_c_boolean epb_brake_and_pull;
  /*
   * EPB激活
   */
  protobuf_c_boolean epb_active;
  /*
   * EPB状态
   */
  EPBState epb_state;
};
#define EPB_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&epb_status__descriptor) \
, NULL, 0, 0, EPBSTATE__EPB_STATE_OFF }


/*
 * ID: 545 - ECON_STATUS 经济模式状态 5Hz
 */
struct  EconStatus
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 经济模式2 [0|3]
   */
  uint32_t econ_on_2;
  /*
   * 经济模式
   */
  protobuf_c_boolean econ_on;
};
#define ECON_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&econ_status__descriptor) \
, NULL, 0, 0 }


/*
 * ID: 597 - ROUGH_WHEEL_SPEED 粗略车轮速度 5Hz
 */
struct  RoughWheelSpeed
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 左前轮速度 [0|255] kph
   */
  uint32_t wheel_speed_fl;
  /*
   * 右前轮速度 [0|255] kph
   */
  uint32_t wheel_speed_fr;
  /*
   * 左后轮速度 [0|255] kph
   */
  uint32_t wheel_speed_rl;
  /*
   * 右后轮速度 [0|255] kph
   */
  uint32_t wheel_speed_rr;
  /*
   * 设置为0x55 [0|255]
   */
  uint32_t set_to_x55;
  /*
   * 设置为0x55_2 [0|255]
   */
  uint32_t set_to_x55_2;
  /*
   * 长计数器 [0|255]
   */
  uint32_t long_counter;
};
#define ROUGH_WHEEL_SPEED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rough_wheel_speed__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0, 0 }


/*
 * ID: 662 - SCM_BUTTONS 方向盘控制按钮 5Hz
 */
struct  ScmButtons
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 巡航按钮
   */
  CruiseButton cruise_buttons;
  /*
   * 巡航设置 [0|3]
   */
  uint32_t cruise_setting;
};
#define SCM_BUTTONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scm_buttons__descriptor) \
, NULL, CRUISE_BUTTON__CRUISE_BUTTON_NONE, 0 }


/*
 * ID: 773 - SEATBELT_STATUS 安全带状态 2.5Hz
 */
struct  SeatbeltStatus
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 驾驶员安全带灯
   */
  protobuf_c_boolean seatbelt_driver_lamp;
  /*
   * 乘客安全带未锁
   */
  protobuf_c_boolean seatbelt_pass_unlatched;
  /*
   * 乘客安全带已锁
   */
  protobuf_c_boolean seatbelt_pass_latched;
  /*
   * 驾驶员安全带未锁
   */
  protobuf_c_boolean seatbelt_driver_unlatched;
  /*
   * 驾驶员安全带已锁
   */
  protobuf_c_boolean seatbelt_driver_latched;
  /*
   * 乘客安全气囊关闭
   */
  protobuf_c_boolean pass_airbag_off;
  /*
   * 乘客安全气囊开启
   */
  protobuf_c_boolean pass_airbag_on;
};
#define SEATBELT_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&seatbelt_status__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0, 0 }


/*
 * ID: 777 - CAR_SPEED 车速 2.5Hz
 */
struct  CarSpeed
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 粗略车速 [0|255] mph
   */
  uint32_t rough_car_speed;
  /*
   * 车速 [0|65535] kph
   */
  float car_speed;
  /*
   * 粗略车速3 [0|65535] kph
   */
  float rough_car_speed_3;
  /*
   * 粗略车速2 [0|255] mph
   */
  uint32_t rough_car_speed_2;
  /*
   * 锁定状态 [0|255]
   */
  uint32_t lock_status;
  /*
   * 英制单位
   */
  protobuf_c_boolean imperial_unit;
};
#define CAR_SPEED__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_speed__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0 }


/*
 * ID: 806 - SCM_FEEDBACK 方向盘控制反馈 2.5Hz
 */
struct  ScmFeedback
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 驾驶员门开
   */
  protobuf_c_boolean drivers_door_open;
  /*
   * 倒车灯
   */
  protobuf_c_boolean reverse_light;
  /*
   * CMBS按钮
   */
  CMBSButton cmbs_button;
  /*
   * 左转向灯
   */
  protobuf_c_boolean left_blinker;
  /*
   * 右转向灯
   */
  protobuf_c_boolean right_blinker;
  /*
   * 主开关开启
   */
  protobuf_c_boolean main_on;
  /*
   * 驻车制动开启
   */
  protobuf_c_boolean parking_brake_on;
};
#define SCM_FEEDBACK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&scm_feedback__descriptor) \
, NULL, 0, 0, CMBSBUTTON__CMBS_BUTTON_RELEASED, 0, 0, 0, 0 }


/*
 * ID: 884 - STALK_STATUS 拨杆状态 2.5Hz
 */
struct  StalkStatus
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 仪表盘警报 [0|255]
   */
  uint32_t dashboard_alert;
  /*
   * 自动头灯
   */
  protobuf_c_boolean auto_headlights;
  /*
   * 远光保持
   */
  protobuf_c_boolean high_beam_hold;
  /*
   * 远光闪烁
   */
  protobuf_c_boolean high_beam_flash;
  /*
   * 头灯开启
   */
  protobuf_c_boolean headlights_on;
  /*
   * 雨刷开关 [0|3]
   */
  uint32_t wiper_switch;
};
#define STALK_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stalk_status__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0 }


/*
 * ID: 891 - STALK_STATUS_2 拨杆状态2 2.5Hz
 */
struct  StalkStatus2
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 雨刷状态
   */
  uint32_t wipers;
  /*
   * 近光灯
   */
  protobuf_c_boolean low_beams;
  /*
   * 远光灯
   */
  protobuf_c_boolean high_beams;
  /*
   * 停车灯
   */
  protobuf_c_boolean park_lights;
};
#define STALK_STATUS2__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&stalk_status2__descriptor) \
, NULL, 0, 0, 0, 0 }


/*
 * ID: 1029 - DOORS_STATUS 车门状态 1Hz
 */
struct  DoorsStatus
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 左前门开
   */
  protobuf_c_boolean door_open_fl;
  /*
   * 右前门开
   */
  protobuf_c_boolean door_open_fr;
  /*
   * 左后门开
   */
  protobuf_c_boolean door_open_rl;
  /*
   * 右后门开
   */
  protobuf_c_boolean door_open_rr;
  /*
   * 行李箱开
   */
  protobuf_c_boolean trunk_open;
};
#define DOORS_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&doors_status__descriptor) \
, NULL, 0, 0, 0, 0, 0 }


/*
 * ID: 1302 - ODOMETER 里程表 1Hz
 */
struct  Odometer
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 里程 [0|16777215] km
   */
  uint32_t odometer;
};
#define ODOMETER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&odometer__descriptor) \
, NULL, 0 }


/*
 * ID: 401 - GEARBOX_CVT CVT变速箱
 */
struct  GearboxCvt
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * P档选择
   */
  protobuf_c_boolean selected_p;
  /*
   * R档选择
   */
  protobuf_c_boolean selected_r;
  /*
   * N档选择
   */
  protobuf_c_boolean selected_n;
  /*
   * D档选择
   */
  protobuf_c_boolean selected_d;
  /*
   * 前进驾驶模式
   */
  protobuf_c_boolean forward_driving_mode;
  /*
   * CVT未知1 [0|255]
   */
  uint32_t cvt_unknown_1;
  /*
   * CVT未知2 [0|255]
   */
  uint32_t cvt_unknown_2;
  /*
   * 档位选择器
   */
  GearShifter gear_shifter;
  /*
   * 换档位置有效
   */
  protobuf_c_boolean shifter_position_valid;
  /*
   * 非前进档
   */
  protobuf_c_boolean not_forward_gear;
  /*
   * CVT未知3 [0|3]
   */
  uint32_t cvt_unknown_3;
};
#define GEARBOX_CVT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gearbox_cvt__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0, 0, GEAR_SHIFTER__GEAR_NONE, 0, 0, 0 }


/*
 * ID: 493 - HUD_SETTING HUD设置
 */
struct  HudSetting
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 英制单位
   */
  protobuf_c_boolean imperial_unit;
};
#define HUD_SETTING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&hud_setting__descriptor) \
, NULL, 0 }


/*
 * ID: 804 - CRUISE 定速巡航数据
 */
struct  CruiseData
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * HUD显示的车速（公里/小时）[0|255]
   */
  uint32_t hud_speed_kph;
  /*
   * HUD显示的车速（英里/小时）[0|255]
   */
  uint32_t hud_speed_mph;
  /*
   * 行程燃油消耗 [0|65535]
   */
  uint32_t trip_fuel_consumed;
  /*
   * PCM设置的巡航速度 [0|255] (255表示未设置速度)
   */
  uint32_t cruise_speed_pcm;
  /*
   * 未知数据2，有符号 [-128|127]
   */
  int32_t boh2;
  /*
   * 未知数据3 [0|255]
   */
  uint32_t boh3;
};
#define CRUISE_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cruise_data__descriptor) \
, NULL, 0, 0, 0, 0, 0, 0 }


/*
 * ENGINE_DATA_3 发动机数据3
 */
struct  EngineData3
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 发动机温度
   */
  uint32_t engine_temp;
  /*
   * 进气温度
   */
  uint32_t intake_temp;
  /*
   * 行程燃油消耗
   */
  float trip_fuel_consumed;
};
#define ENGINE_DATA3__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&engine_data3__descriptor) \
, NULL, 0, 0, 0 }


/*
 * DRIVE_MODES 驾驶模式
 */
struct  DriveModes
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 经济模式
   */
  protobuf_c_boolean econ_on;
};
#define DRIVE_MODES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&drive_modes__descriptor) \
, NULL, 0 }


/*
 * GEARBOX 变速箱
 */
struct  Gearbox
{
  ProtobufCMessage base;
  MessageHeader *header;
  /*
   * 档位选择器 [0|63]
   */
  uint32_t gear_shifter;
};
#define GEARBOX__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&gearbox__descriptor) \
, NULL, 0 }


struct  PCMDATA
{
  ProtobufCMessage base;
  /*
   * 加速踏板2
   */
  GasPedal2 *gaspedal2;
  /*
   * 发动机数据
   */
  EngineData *enginedata;
  /*
   * 车身电机数据
   */
  PowertrainData *powertraindata;
  /*
   * 车速
   */
  CarSpeed *carspeed;
  /*
   * 发动机数据3
   */
  EngineData3 *enginedata3;
  /*
   * 变速箱
   */
  GearboxCvt *gearboxcvt;
  /*
   * 变速箱
   */
  Gearbox *gearbox;
};
#define PCM__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&pcm__data__descriptor) \
, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  VSADATA
{
  ProtobufCMessage base;
  /*
   * 车辆稳定性控制系统状态
   */
  VsaStatus *vsastatus;
  /*
   * 车轮速度
   */
  WheelSpeeds *wheelsspeeds;
  /*
   * 车辆动力学数据
   */
  VehicleDynamics *vehicledynamics;
  /*
   * 粗略车轮速度
   */
  RoughWheelSpeed *roughwheelspeed;
  /*
   * 静止状态
   */
  Standstill *standstill;
};
#define VSA__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&vsa__data__descriptor) \
, NULL, NULL, NULL, NULL, NULL }


struct  EPSDATA
{
  ProtobufCMessage base;
  /*
   * 转向电机扭矩
   */
  SteerMotorTorque *steermotortorque;
  /*
   * 转向传感器数据
   */
  SteeringSensors *steeringsensors;
};
#define EPS__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&eps__data__descriptor) \
, NULL, NULL }


struct  OTHERDATA
{
  ProtobufCMessage base;
  /*
   * 电子驻车制动状态
   */
  EpbStatus *epbstatus;
  /*
   * 经济模式状态
   */
  EconStatus *econstatus;
  /*
   * 方向盘控制反馈
   */
  ScmFeedback *scmfeedback;
  /*
   * 拨杆状态
   */
  StalkStatus *stalkstatus;
  /*
   * 拨杆状态2
   */
  StalkStatus2 *stalkstatus2;
  /*
   * 车门状态
   */
  DoorsStatus *doorsstatus;
  /*
   * 里程表
   */
  Odometer *odometer;
  /*
   * 方向盘控制按钮
   */
  ScmButtons *scmbuttons;
  /*
   * 安全带状态
   */
  SeatbeltStatus *seatbeltstatus;
  /*
   * HUD设置
   */
  HudSetting *hudsetting;
};
#define OTHER__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&other__data__descriptor) \
, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL }


struct  ALLDATA
{
  ProtobufCMessage base;
  /*
   * PCM数据
   */
  PCMDATA *pcmdata;
  /*
   * VSA数据
   */
  VSADATA *vsadata;
  /*
   * EPS数据
   */
  EPSDATA *epsdata;
  /*
   * 其他数据
   */
  OTHERDATA *otherdata;
};
#define ALL__DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&all__data__descriptor) \
, NULL, NULL, NULL, NULL }


typedef enum {
  CAR_STATUS__POWERTRAIN_DATA__NOT_SET = 0,
  CAR_STATUS__POWERTRAIN_DATA_POWERTRAIN = 380
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__POWERTRAIN_DATA__CASE)
} CarStatus__PowertrainDataCase;

typedef enum {
  CAR_STATUS__ENGINE_DATA__NOT_SET = 0,
  CAR_STATUS__ENGINE_DATA_ENGINE = 344
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__ENGINE_DATA__CASE)
} CarStatus__EngineDataCase;

typedef enum {
  CAR_STATUS__GAS_PEDAL_2_DATA__NOT_SET = 0,
  CAR_STATUS__GAS_PEDAL_2_DATA_GAS_PEDAL2 = 304
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__GAS_PEDAL_2_DATA__CASE)
} CarStatus__GasPedal2DataCase;

typedef enum {
  CAR_STATUS__STEERING_DATA__NOT_SET = 0,
  CAR_STATUS__STEERING_DATA_STEERING_SENSORS = 330
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__STEERING_DATA__CASE)
} CarStatus__SteeringDataCase;

typedef enum {
  CAR_STATUS__KINEMATICS_DATA__NOT_SET = 0,
  CAR_STATUS__KINEMATICS_DATA_KINEMATICS_ALT = 148
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__KINEMATICS_DATA__CASE)
} CarStatus__KinematicsDataCase;

typedef enum {
  CAR_STATUS__VSA_STATUS_DATA__NOT_SET = 0,
  CAR_STATUS__VSA_STATUS_DATA_VSA_STATUS = 420
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__VSA_STATUS_DATA__CASE)
} CarStatus__VsaStatusDataCase;

typedef enum {
  CAR_STATUS__STANDSTILL_DATA__NOT_SET = 0,
  CAR_STATUS__STANDSTILL_DATA_STANDSTILL = 432
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__STANDSTILL_DATA__CASE)
} CarStatus__StandstillDataCase;

typedef enum {
  CAR_STATUS__WHEEL_SPEEDS_DATA__NOT_SET = 0,
  CAR_STATUS__WHEEL_SPEEDS_DATA_WHEELS_SPEEDS = 464
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__WHEEL_SPEEDS_DATA__CASE)
} CarStatus__WheelSpeedsDataCase;

typedef enum {
  CAR_STATUS__VEHICLE_DYNAMICS_DATA__NOT_SET = 0,
  CAR_STATUS__VEHICLE_DYNAMICS_DATA_DYNAMICS = 490
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__VEHICLE_DYNAMICS_DATA__CASE)
} CarStatus__VehicleDynamicsDataCase;

typedef enum {
  CAR_STATUS__STEER_MOTOR_TORQUE_DATA__NOT_SET = 0,
  CAR_STATUS__STEER_MOTOR_TORQUE_DATA_STEER_MOTOR_TORQUE = 427
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__STEER_MOTOR_TORQUE_DATA__CASE)
} CarStatus__SteerMotorTorqueDataCase;

typedef enum {
  CAR_STATUS__EPB_STATUS_DATA__NOT_SET = 0,
  CAR_STATUS__EPB_STATUS_DATA_EPB_STATUS = 450
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__EPB_STATUS_DATA__CASE)
} CarStatus__EpbStatusDataCase;

typedef enum {
  CAR_STATUS__ECON_STATUS_DATA__NOT_SET = 0,
  CAR_STATUS__ECON_STATUS_DATA_ECON_STATUS = 545
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__ECON_STATUS_DATA__CASE)
} CarStatus__EconStatusDataCase;

typedef enum {
  CAR_STATUS__ROUGH_WHEEL_SPEED_DATA__NOT_SET = 0,
  CAR_STATUS__ROUGH_WHEEL_SPEED_DATA_ROUGH_WHEEL_SPEED = 597
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__ROUGH_WHEEL_SPEED_DATA__CASE)
} CarStatus__RoughWheelSpeedDataCase;

typedef enum {
  CAR_STATUS__SCM_BUTTONS_DATA__NOT_SET = 0,
  CAR_STATUS__SCM_BUTTONS_DATA_SCM_BUTTONS = 662
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__SCM_BUTTONS_DATA__CASE)
} CarStatus__ScmButtonsDataCase;

typedef enum {
  CAR_STATUS__SEATBELT_STATUS_DATA__NOT_SET = 0,
  CAR_STATUS__SEATBELT_STATUS_DATA_SEATBELT_STATUS = 773
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__SEATBELT_STATUS_DATA__CASE)
} CarStatus__SeatbeltStatusDataCase;

typedef enum {
  CAR_STATUS__CAR_SPEED_DATA__NOT_SET = 0,
  CAR_STATUS__CAR_SPEED_DATA_CAR_SPEED = 777
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__CAR_SPEED_DATA__CASE)
} CarStatus__CarSpeedDataCase;

typedef enum {
  CAR_STATUS__SCM_FEEDBACK_DATA__NOT_SET = 0,
  CAR_STATUS__SCM_FEEDBACK_DATA_SCM_FEEDBACK = 806
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__SCM_FEEDBACK_DATA__CASE)
} CarStatus__ScmFeedbackDataCase;

typedef enum {
  CAR_STATUS__STALK_STATUS_DATA__NOT_SET = 0,
  CAR_STATUS__STALK_STATUS_DATA_STALK_STATUS = 884
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__STALK_STATUS_DATA__CASE)
} CarStatus__StalkStatusDataCase;

typedef enum {
  CAR_STATUS__STALK_STATUS_2_DATA__NOT_SET = 0,
  CAR_STATUS__STALK_STATUS_2_DATA_STALK_STATUS2 = 891
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__STALK_STATUS_2_DATA__CASE)
} CarStatus__StalkStatus2DataCase;

typedef enum {
  CAR_STATUS__DOORS_STATUS_DATA__NOT_SET = 0,
  CAR_STATUS__DOORS_STATUS_DATA_DOORS_STATUS = 1029
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__DOORS_STATUS_DATA__CASE)
} CarStatus__DoorsStatusDataCase;

typedef enum {
  CAR_STATUS__ODOMETER_DATA__NOT_SET = 0,
  CAR_STATUS__ODOMETER_DATA_ODOMETER = 1302
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__ODOMETER_DATA__CASE)
} CarStatus__OdometerDataCase;

typedef enum {
  CAR_STATUS__GEARBOX_CVT_DATA__NOT_SET = 0,
  CAR_STATUS__GEARBOX_CVT_DATA_GEARBOX_CVT = 401
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__GEARBOX_CVT_DATA__CASE)
} CarStatus__GearboxCvtDataCase;

typedef enum {
  CAR_STATUS__HUD_SETTING_DATA__NOT_SET = 0,
  CAR_STATUS__HUD_SETTING_DATA_HUD_SETTING = 493
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__HUD_SETTING_DATA__CASE)
} CarStatus__HudSettingDataCase;

typedef enum {
  CAR_STATUS__ENGINE_DATA_3__NOT_SET = 0,
  CAR_STATUS__ENGINE_DATA_3_ENGINE_DATA3 = 804
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAR_STATUS__ENGINE_DATA_3__CASE)
} CarStatus__EngineData3Case;

/*
 * 车辆状态聚合消息，包含所有数据
 */
struct  CarStatus
{
  ProtobufCMessage base;
  /*
   *google.protobuf.Timestamp timestamp = 1;
   */
  /*
   * 时间戳，单位：微秒
   */
  uint64_t timestamp;
  CarStatus__PowertrainDataCase powertrain_data_case;
  union {
    PowertrainData *powertrain;
  };
  CarStatus__EngineDataCase engine_data_case;
  union {
    EngineData *engine;
  };
  CarStatus__GasPedal2DataCase gas_pedal_2_data_case;
  union {
    GasPedal2 *gaspedal2;
  };
  CarStatus__SteeringDataCase steering_data_case;
  union {
    SteeringSensors *steeringsensors;
  };
  CarStatus__KinematicsDataCase kinematics_data_case;
  union {
    KinematicsAlt *kinematicsalt;
  };
  CarStatus__VsaStatusDataCase vsa_status_data_case;
  union {
    VsaStatus *vsastatus;
  };
  CarStatus__StandstillDataCase standstill_data_case;
  union {
    Standstill *standstill;
  };
  CarStatus__WheelSpeedsDataCase wheel_speeds_data_case;
  union {
    WheelSpeeds *wheelsspeeds;
  };
  CarStatus__VehicleDynamicsDataCase vehicle_dynamics_data_case;
  union {
    VehicleDynamics *dynamics;
  };
  CarStatus__SteerMotorTorqueDataCase steer_motor_torque_data_case;
  union {
    SteerMotorTorque *steermotortorque;
  };
  CarStatus__EpbStatusDataCase epb_status_data_case;
  union {
    EpbStatus *epbstatus;
  };
  CarStatus__EconStatusDataCase econ_status_data_case;
  union {
    EconStatus *econstatus;
  };
  CarStatus__RoughWheelSpeedDataCase rough_wheel_speed_data_case;
  union {
    RoughWheelSpeed *roughwheelspeed;
  };
  CarStatus__ScmButtonsDataCase scm_buttons_data_case;
  union {
    ScmButtons *scmbuttons;
  };
  CarStatus__SeatbeltStatusDataCase seatbelt_status_data_case;
  union {
    SeatbeltStatus *seatbeltstatus;
  };
  CarStatus__CarSpeedDataCase car_speed_data_case;
  union {
    CarSpeed *carspeed;
  };
  CarStatus__ScmFeedbackDataCase scm_feedback_data_case;
  union {
    ScmFeedback *scmfeedback;
  };
  CarStatus__StalkStatusDataCase stalk_status_data_case;
  union {
    StalkStatus *stalkstatus;
  };
  CarStatus__StalkStatus2DataCase stalk_status_2_data_case;
  union {
    StalkStatus2 *stalkstatus2;
  };
  CarStatus__DoorsStatusDataCase doors_status_data_case;
  union {
    DoorsStatus *doorsstatus;
  };
  CarStatus__OdometerDataCase odometer_data_case;
  union {
    Odometer *odometer;
  };
  CarStatus__GearboxCvtDataCase gearbox_cvt_data_case;
  union {
    GearboxCvt *gearboxcvt;
  };
  CarStatus__HudSettingDataCase hud_setting_data_case;
  union {
    HudSetting *hudsetting;
  };
  CarStatus__EngineData3Case engine_data_3_case;
  union {
    EngineData3 *enginedata3;
  };
};
#define CAR_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&car_status__descriptor) \
, 0, CAR_STATUS__POWERTRAIN_DATA__NOT_SET, {0}, CAR_STATUS__ENGINE_DATA__NOT_SET, {0}, CAR_STATUS__GAS_PEDAL_2_DATA__NOT_SET, {0}, CAR_STATUS__STEERING_DATA__NOT_SET, {0}, CAR_STATUS__KINEMATICS_DATA__NOT_SET, {0}, CAR_STATUS__VSA_STATUS_DATA__NOT_SET, {0}, CAR_STATUS__STANDSTILL_DATA__NOT_SET, {0}, CAR_STATUS__WHEEL_SPEEDS_DATA__NOT_SET, {0}, CAR_STATUS__VEHICLE_DYNAMICS_DATA__NOT_SET, {0}, CAR_STATUS__STEER_MOTOR_TORQUE_DATA__NOT_SET, {0}, CAR_STATUS__EPB_STATUS_DATA__NOT_SET, {0}, CAR_STATUS__ECON_STATUS_DATA__NOT_SET, {0}, CAR_STATUS__ROUGH_WHEEL_SPEED_DATA__NOT_SET, {0}, CAR_STATUS__SCM_BUTTONS_DATA__NOT_SET, {0}, CAR_STATUS__SEATBELT_STATUS_DATA__NOT_SET, {0}, CAR_STATUS__CAR_SPEED_DATA__NOT_SET, {0}, CAR_STATUS__SCM_FEEDBACK_DATA__NOT_SET, {0}, CAR_STATUS__STALK_STATUS_DATA__NOT_SET, {0}, CAR_STATUS__STALK_STATUS_2_DATA__NOT_SET, {0}, CAR_STATUS__DOORS_STATUS_DATA__NOT_SET, {0}, CAR_STATUS__ODOMETER_DATA__NOT_SET, {0}, CAR_STATUS__GEARBOX_CVT_DATA__NOT_SET, {0}, CAR_STATUS__HUD_SETTING_DATA__NOT_SET, {0}, CAR_STATUS__ENGINE_DATA_3__NOT_SET, {0} }


/*
 * 批量数据消息，用于存储时间序列
 */
struct  VehicleDataBatch
{
  ProtobufCMessage base;
  size_t n_data_points;
  CarStatus **data_points;
};
#define VEHICLE_DATA_BATCH__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&vehicle_data_batch__descriptor) \
, 0,NULL }


/*
 * CAN原始数据消息
 */
struct  CanData
{
  ProtobufCMessage base;
  uint32_t can_id;
  /*
   *google.protobuf.Timestamp timestamp = 3;
   */
  ProtobufCBinaryData raw_data;
};
#define CAN_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&can_data__descriptor) \
, 0, {0,NULL} }


/* MessageHeader methods */
void   message_header__init
                     (MessageHeader         *message);
size_t message_header__get_packed_size
                     (const MessageHeader   *message);
size_t message_header__pack
                     (const MessageHeader   *message,
                      uint8_t             *out);
size_t message_header__pack_to_buffer
                     (const MessageHeader   *message,
                      ProtobufCBuffer     *buffer);
MessageHeader *
       message_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   message_header__free_unpacked
                     (MessageHeader *message,
                      ProtobufCAllocator *allocator);
/* PowertrainData methods */
void   powertrain_data__init
                     (PowertrainData         *message);
size_t powertrain_data__get_packed_size
                     (const PowertrainData   *message);
size_t powertrain_data__pack
                     (const PowertrainData   *message,
                      uint8_t             *out);
size_t powertrain_data__pack_to_buffer
                     (const PowertrainData   *message,
                      ProtobufCBuffer     *buffer);
PowertrainData *
       powertrain_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   powertrain_data__free_unpacked
                     (PowertrainData *message,
                      ProtobufCAllocator *allocator);
/* EngineData methods */
void   engine_data__init
                     (EngineData         *message);
size_t engine_data__get_packed_size
                     (const EngineData   *message);
size_t engine_data__pack
                     (const EngineData   *message,
                      uint8_t             *out);
size_t engine_data__pack_to_buffer
                     (const EngineData   *message,
                      ProtobufCBuffer     *buffer);
EngineData *
       engine_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   engine_data__free_unpacked
                     (EngineData *message,
                      ProtobufCAllocator *allocator);
/* GasPedal2 methods */
void   gas_pedal2__init
                     (GasPedal2         *message);
size_t gas_pedal2__get_packed_size
                     (const GasPedal2   *message);
size_t gas_pedal2__pack
                     (const GasPedal2   *message,
                      uint8_t             *out);
size_t gas_pedal2__pack_to_buffer
                     (const GasPedal2   *message,
                      ProtobufCBuffer     *buffer);
GasPedal2 *
       gas_pedal2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gas_pedal2__free_unpacked
                     (GasPedal2 *message,
                      ProtobufCAllocator *allocator);
/* SteeringSensors methods */
void   steering_sensors__init
                     (SteeringSensors         *message);
size_t steering_sensors__get_packed_size
                     (const SteeringSensors   *message);
size_t steering_sensors__pack
                     (const SteeringSensors   *message,
                      uint8_t             *out);
size_t steering_sensors__pack_to_buffer
                     (const SteeringSensors   *message,
                      ProtobufCBuffer     *buffer);
SteeringSensors *
       steering_sensors__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   steering_sensors__free_unpacked
                     (SteeringSensors *message,
                      ProtobufCAllocator *allocator);
/* KinematicsAlt methods */
void   kinematics_alt__init
                     (KinematicsAlt         *message);
size_t kinematics_alt__get_packed_size
                     (const KinematicsAlt   *message);
size_t kinematics_alt__pack
                     (const KinematicsAlt   *message,
                      uint8_t             *out);
size_t kinematics_alt__pack_to_buffer
                     (const KinematicsAlt   *message,
                      ProtobufCBuffer     *buffer);
KinematicsAlt *
       kinematics_alt__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   kinematics_alt__free_unpacked
                     (KinematicsAlt *message,
                      ProtobufCAllocator *allocator);
/* VsaStatus methods */
void   vsa_status__init
                     (VsaStatus         *message);
size_t vsa_status__get_packed_size
                     (const VsaStatus   *message);
size_t vsa_status__pack
                     (const VsaStatus   *message,
                      uint8_t             *out);
size_t vsa_status__pack_to_buffer
                     (const VsaStatus   *message,
                      ProtobufCBuffer     *buffer);
VsaStatus *
       vsa_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   vsa_status__free_unpacked
                     (VsaStatus *message,
                      ProtobufCAllocator *allocator);
/* Standstill methods */
void   standstill__init
                     (Standstill         *message);
size_t standstill__get_packed_size
                     (const Standstill   *message);
size_t standstill__pack
                     (const Standstill   *message,
                      uint8_t             *out);
size_t standstill__pack_to_buffer
                     (const Standstill   *message,
                      ProtobufCBuffer     *buffer);
Standstill *
       standstill__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   standstill__free_unpacked
                     (Standstill *message,
                      ProtobufCAllocator *allocator);
/* WheelSpeeds methods */
void   wheel_speeds__init
                     (WheelSpeeds         *message);
size_t wheel_speeds__get_packed_size
                     (const WheelSpeeds   *message);
size_t wheel_speeds__pack
                     (const WheelSpeeds   *message,
                      uint8_t             *out);
size_t wheel_speeds__pack_to_buffer
                     (const WheelSpeeds   *message,
                      ProtobufCBuffer     *buffer);
WheelSpeeds *
       wheel_speeds__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   wheel_speeds__free_unpacked
                     (WheelSpeeds *message,
                      ProtobufCAllocator *allocator);
/* VehicleDynamics methods */
void   vehicle_dynamics__init
                     (VehicleDynamics         *message);
size_t vehicle_dynamics__get_packed_size
                     (const VehicleDynamics   *message);
size_t vehicle_dynamics__pack
                     (const VehicleDynamics   *message,
                      uint8_t             *out);
size_t vehicle_dynamics__pack_to_buffer
                     (const VehicleDynamics   *message,
                      ProtobufCBuffer     *buffer);
VehicleDynamics *
       vehicle_dynamics__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   vehicle_dynamics__free_unpacked
                     (VehicleDynamics *message,
                      ProtobufCAllocator *allocator);
/* SteerMotorTorque methods */
void   steer_motor_torque__init
                     (SteerMotorTorque         *message);
size_t steer_motor_torque__get_packed_size
                     (const SteerMotorTorque   *message);
size_t steer_motor_torque__pack
                     (const SteerMotorTorque   *message,
                      uint8_t             *out);
size_t steer_motor_torque__pack_to_buffer
                     (const SteerMotorTorque   *message,
                      ProtobufCBuffer     *buffer);
SteerMotorTorque *
       steer_motor_torque__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   steer_motor_torque__free_unpacked
                     (SteerMotorTorque *message,
                      ProtobufCAllocator *allocator);
/* EpbStatus methods */
void   epb_status__init
                     (EpbStatus         *message);
size_t epb_status__get_packed_size
                     (const EpbStatus   *message);
size_t epb_status__pack
                     (const EpbStatus   *message,
                      uint8_t             *out);
size_t epb_status__pack_to_buffer
                     (const EpbStatus   *message,
                      ProtobufCBuffer     *buffer);
EpbStatus *
       epb_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   epb_status__free_unpacked
                     (EpbStatus *message,
                      ProtobufCAllocator *allocator);
/* EconStatus methods */
void   econ_status__init
                     (EconStatus         *message);
size_t econ_status__get_packed_size
                     (const EconStatus   *message);
size_t econ_status__pack
                     (const EconStatus   *message,
                      uint8_t             *out);
size_t econ_status__pack_to_buffer
                     (const EconStatus   *message,
                      ProtobufCBuffer     *buffer);
EconStatus *
       econ_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   econ_status__free_unpacked
                     (EconStatus *message,
                      ProtobufCAllocator *allocator);
/* RoughWheelSpeed methods */
void   rough_wheel_speed__init
                     (RoughWheelSpeed         *message);
size_t rough_wheel_speed__get_packed_size
                     (const RoughWheelSpeed   *message);
size_t rough_wheel_speed__pack
                     (const RoughWheelSpeed   *message,
                      uint8_t             *out);
size_t rough_wheel_speed__pack_to_buffer
                     (const RoughWheelSpeed   *message,
                      ProtobufCBuffer     *buffer);
RoughWheelSpeed *
       rough_wheel_speed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rough_wheel_speed__free_unpacked
                     (RoughWheelSpeed *message,
                      ProtobufCAllocator *allocator);
/* ScmButtons methods */
void   scm_buttons__init
                     (ScmButtons         *message);
size_t scm_buttons__get_packed_size
                     (const ScmButtons   *message);
size_t scm_buttons__pack
                     (const ScmButtons   *message,
                      uint8_t             *out);
size_t scm_buttons__pack_to_buffer
                     (const ScmButtons   *message,
                      ProtobufCBuffer     *buffer);
ScmButtons *
       scm_buttons__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scm_buttons__free_unpacked
                     (ScmButtons *message,
                      ProtobufCAllocator *allocator);
/* SeatbeltStatus methods */
void   seatbelt_status__init
                     (SeatbeltStatus         *message);
size_t seatbelt_status__get_packed_size
                     (const SeatbeltStatus   *message);
size_t seatbelt_status__pack
                     (const SeatbeltStatus   *message,
                      uint8_t             *out);
size_t seatbelt_status__pack_to_buffer
                     (const SeatbeltStatus   *message,
                      ProtobufCBuffer     *buffer);
SeatbeltStatus *
       seatbelt_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   seatbelt_status__free_unpacked
                     (SeatbeltStatus *message,
                      ProtobufCAllocator *allocator);
/* CarSpeed methods */
void   car_speed__init
                     (CarSpeed         *message);
size_t car_speed__get_packed_size
                     (const CarSpeed   *message);
size_t car_speed__pack
                     (const CarSpeed   *message,
                      uint8_t             *out);
size_t car_speed__pack_to_buffer
                     (const CarSpeed   *message,
                      ProtobufCBuffer     *buffer);
CarSpeed *
       car_speed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_speed__free_unpacked
                     (CarSpeed *message,
                      ProtobufCAllocator *allocator);
/* ScmFeedback methods */
void   scm_feedback__init
                     (ScmFeedback         *message);
size_t scm_feedback__get_packed_size
                     (const ScmFeedback   *message);
size_t scm_feedback__pack
                     (const ScmFeedback   *message,
                      uint8_t             *out);
size_t scm_feedback__pack_to_buffer
                     (const ScmFeedback   *message,
                      ProtobufCBuffer     *buffer);
ScmFeedback *
       scm_feedback__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   scm_feedback__free_unpacked
                     (ScmFeedback *message,
                      ProtobufCAllocator *allocator);
/* StalkStatus methods */
void   stalk_status__init
                     (StalkStatus         *message);
size_t stalk_status__get_packed_size
                     (const StalkStatus   *message);
size_t stalk_status__pack
                     (const StalkStatus   *message,
                      uint8_t             *out);
size_t stalk_status__pack_to_buffer
                     (const StalkStatus   *message,
                      ProtobufCBuffer     *buffer);
StalkStatus *
       stalk_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stalk_status__free_unpacked
                     (StalkStatus *message,
                      ProtobufCAllocator *allocator);
/* StalkStatus2 methods */
void   stalk_status2__init
                     (StalkStatus2         *message);
size_t stalk_status2__get_packed_size
                     (const StalkStatus2   *message);
size_t stalk_status2__pack
                     (const StalkStatus2   *message,
                      uint8_t             *out);
size_t stalk_status2__pack_to_buffer
                     (const StalkStatus2   *message,
                      ProtobufCBuffer     *buffer);
StalkStatus2 *
       stalk_status2__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   stalk_status2__free_unpacked
                     (StalkStatus2 *message,
                      ProtobufCAllocator *allocator);
/* DoorsStatus methods */
void   doors_status__init
                     (DoorsStatus         *message);
size_t doors_status__get_packed_size
                     (const DoorsStatus   *message);
size_t doors_status__pack
                     (const DoorsStatus   *message,
                      uint8_t             *out);
size_t doors_status__pack_to_buffer
                     (const DoorsStatus   *message,
                      ProtobufCBuffer     *buffer);
DoorsStatus *
       doors_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   doors_status__free_unpacked
                     (DoorsStatus *message,
                      ProtobufCAllocator *allocator);
/* Odometer methods */
void   odometer__init
                     (Odometer         *message);
size_t odometer__get_packed_size
                     (const Odometer   *message);
size_t odometer__pack
                     (const Odometer   *message,
                      uint8_t             *out);
size_t odometer__pack_to_buffer
                     (const Odometer   *message,
                      ProtobufCBuffer     *buffer);
Odometer *
       odometer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   odometer__free_unpacked
                     (Odometer *message,
                      ProtobufCAllocator *allocator);
/* GearboxCvt methods */
void   gearbox_cvt__init
                     (GearboxCvt         *message);
size_t gearbox_cvt__get_packed_size
                     (const GearboxCvt   *message);
size_t gearbox_cvt__pack
                     (const GearboxCvt   *message,
                      uint8_t             *out);
size_t gearbox_cvt__pack_to_buffer
                     (const GearboxCvt   *message,
                      ProtobufCBuffer     *buffer);
GearboxCvt *
       gearbox_cvt__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gearbox_cvt__free_unpacked
                     (GearboxCvt *message,
                      ProtobufCAllocator *allocator);
/* HudSetting methods */
void   hud_setting__init
                     (HudSetting         *message);
size_t hud_setting__get_packed_size
                     (const HudSetting   *message);
size_t hud_setting__pack
                     (const HudSetting   *message,
                      uint8_t             *out);
size_t hud_setting__pack_to_buffer
                     (const HudSetting   *message,
                      ProtobufCBuffer     *buffer);
HudSetting *
       hud_setting__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   hud_setting__free_unpacked
                     (HudSetting *message,
                      ProtobufCAllocator *allocator);
/* CruiseData methods */
void   cruise_data__init
                     (CruiseData         *message);
size_t cruise_data__get_packed_size
                     (const CruiseData   *message);
size_t cruise_data__pack
                     (const CruiseData   *message,
                      uint8_t             *out);
size_t cruise_data__pack_to_buffer
                     (const CruiseData   *message,
                      ProtobufCBuffer     *buffer);
CruiseData *
       cruise_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cruise_data__free_unpacked
                     (CruiseData *message,
                      ProtobufCAllocator *allocator);
/* EngineData3 methods */
void   engine_data3__init
                     (EngineData3         *message);
size_t engine_data3__get_packed_size
                     (const EngineData3   *message);
size_t engine_data3__pack
                     (const EngineData3   *message,
                      uint8_t             *out);
size_t engine_data3__pack_to_buffer
                     (const EngineData3   *message,
                      ProtobufCBuffer     *buffer);
EngineData3 *
       engine_data3__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   engine_data3__free_unpacked
                     (EngineData3 *message,
                      ProtobufCAllocator *allocator);
/* DriveModes methods */
void   drive_modes__init
                     (DriveModes         *message);
size_t drive_modes__get_packed_size
                     (const DriveModes   *message);
size_t drive_modes__pack
                     (const DriveModes   *message,
                      uint8_t             *out);
size_t drive_modes__pack_to_buffer
                     (const DriveModes   *message,
                      ProtobufCBuffer     *buffer);
DriveModes *
       drive_modes__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   drive_modes__free_unpacked
                     (DriveModes *message,
                      ProtobufCAllocator *allocator);
/* Gearbox methods */
void   gearbox__init
                     (Gearbox         *message);
size_t gearbox__get_packed_size
                     (const Gearbox   *message);
size_t gearbox__pack
                     (const Gearbox   *message,
                      uint8_t             *out);
size_t gearbox__pack_to_buffer
                     (const Gearbox   *message,
                      ProtobufCBuffer     *buffer);
Gearbox *
       gearbox__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   gearbox__free_unpacked
                     (Gearbox *message,
                      ProtobufCAllocator *allocator);
/* PCMDATA methods */
void   pcm__data__init
                     (PCMDATA         *message);
size_t pcm__data__get_packed_size
                     (const PCMDATA   *message);
size_t pcm__data__pack
                     (const PCMDATA   *message,
                      uint8_t             *out);
size_t pcm__data__pack_to_buffer
                     (const PCMDATA   *message,
                      ProtobufCBuffer     *buffer);
PCMDATA *
       pcm__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   pcm__data__free_unpacked
                     (PCMDATA *message,
                      ProtobufCAllocator *allocator);
/* VSADATA methods */
void   vsa__data__init
                     (VSADATA         *message);
size_t vsa__data__get_packed_size
                     (const VSADATA   *message);
size_t vsa__data__pack
                     (const VSADATA   *message,
                      uint8_t             *out);
size_t vsa__data__pack_to_buffer
                     (const VSADATA   *message,
                      ProtobufCBuffer     *buffer);
VSADATA *
       vsa__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   vsa__data__free_unpacked
                     (VSADATA *message,
                      ProtobufCAllocator *allocator);
/* EPSDATA methods */
void   eps__data__init
                     (EPSDATA         *message);
size_t eps__data__get_packed_size
                     (const EPSDATA   *message);
size_t eps__data__pack
                     (const EPSDATA   *message,
                      uint8_t             *out);
size_t eps__data__pack_to_buffer
                     (const EPSDATA   *message,
                      ProtobufCBuffer     *buffer);
EPSDATA *
       eps__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   eps__data__free_unpacked
                     (EPSDATA *message,
                      ProtobufCAllocator *allocator);
/* OTHERDATA methods */
void   other__data__init
                     (OTHERDATA         *message);
size_t other__data__get_packed_size
                     (const OTHERDATA   *message);
size_t other__data__pack
                     (const OTHERDATA   *message,
                      uint8_t             *out);
size_t other__data__pack_to_buffer
                     (const OTHERDATA   *message,
                      ProtobufCBuffer     *buffer);
OTHERDATA *
       other__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   other__data__free_unpacked
                     (OTHERDATA *message,
                      ProtobufCAllocator *allocator);
/* ALLDATA methods */
void   all__data__init
                     (ALLDATA         *message);
size_t all__data__get_packed_size
                     (const ALLDATA   *message);
size_t all__data__pack
                     (const ALLDATA   *message,
                      uint8_t             *out);
size_t all__data__pack_to_buffer
                     (const ALLDATA   *message,
                      ProtobufCBuffer     *buffer);
ALLDATA *
       all__data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   all__data__free_unpacked
                     (ALLDATA *message,
                      ProtobufCAllocator *allocator);
/* CarStatus methods */
void   car_status__init
                     (CarStatus         *message);
size_t car_status__get_packed_size
                     (const CarStatus   *message);
size_t car_status__pack
                     (const CarStatus   *message,
                      uint8_t             *out);
size_t car_status__pack_to_buffer
                     (const CarStatus   *message,
                      ProtobufCBuffer     *buffer);
CarStatus *
       car_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   car_status__free_unpacked
                     (CarStatus *message,
                      ProtobufCAllocator *allocator);
/* VehicleDataBatch methods */
void   vehicle_data_batch__init
                     (VehicleDataBatch         *message);
size_t vehicle_data_batch__get_packed_size
                     (const VehicleDataBatch   *message);
size_t vehicle_data_batch__pack
                     (const VehicleDataBatch   *message,
                      uint8_t             *out);
size_t vehicle_data_batch__pack_to_buffer
                     (const VehicleDataBatch   *message,
                      ProtobufCBuffer     *buffer);
VehicleDataBatch *
       vehicle_data_batch__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   vehicle_data_batch__free_unpacked
                     (VehicleDataBatch *message,
                      ProtobufCAllocator *allocator);
/* CanData methods */
void   can_data__init
                     (CanData         *message);
size_t can_data__get_packed_size
                     (const CanData   *message);
size_t can_data__pack
                     (const CanData   *message,
                      uint8_t             *out);
size_t can_data__pack_to_buffer
                     (const CanData   *message,
                      ProtobufCBuffer     *buffer);
CanData *
       can_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   can_data__free_unpacked
                     (CanData *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MessageHeader_Closure)
                 (const MessageHeader *message,
                  void *closure_data);
typedef void (*PowertrainData_Closure)
                 (const PowertrainData *message,
                  void *closure_data);
typedef void (*EngineData_Closure)
                 (const EngineData *message,
                  void *closure_data);
typedef void (*GasPedal2_Closure)
                 (const GasPedal2 *message,
                  void *closure_data);
typedef void (*SteeringSensors_Closure)
                 (const SteeringSensors *message,
                  void *closure_data);
typedef void (*KinematicsAlt_Closure)
                 (const KinematicsAlt *message,
                  void *closure_data);
typedef void (*VsaStatus_Closure)
                 (const VsaStatus *message,
                  void *closure_data);
typedef void (*Standstill_Closure)
                 (const Standstill *message,
                  void *closure_data);
typedef void (*WheelSpeeds_Closure)
                 (const WheelSpeeds *message,
                  void *closure_data);
typedef void (*VehicleDynamics_Closure)
                 (const VehicleDynamics *message,
                  void *closure_data);
typedef void (*SteerMotorTorque_Closure)
                 (const SteerMotorTorque *message,
                  void *closure_data);
typedef void (*EpbStatus_Closure)
                 (const EpbStatus *message,
                  void *closure_data);
typedef void (*EconStatus_Closure)
                 (const EconStatus *message,
                  void *closure_data);
typedef void (*RoughWheelSpeed_Closure)
                 (const RoughWheelSpeed *message,
                  void *closure_data);
typedef void (*ScmButtons_Closure)
                 (const ScmButtons *message,
                  void *closure_data);
typedef void (*SeatbeltStatus_Closure)
                 (const SeatbeltStatus *message,
                  void *closure_data);
typedef void (*CarSpeed_Closure)
                 (const CarSpeed *message,
                  void *closure_data);
typedef void (*ScmFeedback_Closure)
                 (const ScmFeedback *message,
                  void *closure_data);
typedef void (*StalkStatus_Closure)
                 (const StalkStatus *message,
                  void *closure_data);
typedef void (*StalkStatus2_Closure)
                 (const StalkStatus2 *message,
                  void *closure_data);
typedef void (*DoorsStatus_Closure)
                 (const DoorsStatus *message,
                  void *closure_data);
typedef void (*Odometer_Closure)
                 (const Odometer *message,
                  void *closure_data);
typedef void (*GearboxCvt_Closure)
                 (const GearboxCvt *message,
                  void *closure_data);
typedef void (*HudSetting_Closure)
                 (const HudSetting *message,
                  void *closure_data);
typedef void (*CruiseData_Closure)
                 (const CruiseData *message,
                  void *closure_data);
typedef void (*EngineData3_Closure)
                 (const EngineData3 *message,
                  void *closure_data);
typedef void (*DriveModes_Closure)
                 (const DriveModes *message,
                  void *closure_data);
typedef void (*Gearbox_Closure)
                 (const Gearbox *message,
                  void *closure_data);
typedef void (*PCMDATA_Closure)
                 (const PCMDATA *message,
                  void *closure_data);
typedef void (*VSADATA_Closure)
                 (const VSADATA *message,
                  void *closure_data);
typedef void (*EPSDATA_Closure)
                 (const EPSDATA *message,
                  void *closure_data);
typedef void (*OTHERDATA_Closure)
                 (const OTHERDATA *message,
                  void *closure_data);
typedef void (*ALLDATA_Closure)
                 (const ALLDATA *message,
                  void *closure_data);
typedef void (*CarStatus_Closure)
                 (const CarStatus *message,
                  void *closure_data);
typedef void (*VehicleDataBatch_Closure)
                 (const VehicleDataBatch *message,
                  void *closure_data);
typedef void (*CanData_Closure)
                 (const CanData *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    epbstate__descriptor;
extern const ProtobufCEnumDescriptor    cruise_button__descriptor;
extern const ProtobufCEnumDescriptor    cmbsbutton__descriptor;
extern const ProtobufCEnumDescriptor    gear_shifter__descriptor;
extern const ProtobufCEnumDescriptor    wiper_status__descriptor;
extern const ProtobufCMessageDescriptor message_header__descriptor;
extern const ProtobufCMessageDescriptor powertrain_data__descriptor;
extern const ProtobufCMessageDescriptor engine_data__descriptor;
extern const ProtobufCMessageDescriptor gas_pedal2__descriptor;
extern const ProtobufCMessageDescriptor steering_sensors__descriptor;
extern const ProtobufCMessageDescriptor kinematics_alt__descriptor;
extern const ProtobufCMessageDescriptor vsa_status__descriptor;
extern const ProtobufCMessageDescriptor standstill__descriptor;
extern const ProtobufCMessageDescriptor wheel_speeds__descriptor;
extern const ProtobufCMessageDescriptor vehicle_dynamics__descriptor;
extern const ProtobufCMessageDescriptor steer_motor_torque__descriptor;
extern const ProtobufCMessageDescriptor epb_status__descriptor;
extern const ProtobufCMessageDescriptor econ_status__descriptor;
extern const ProtobufCMessageDescriptor rough_wheel_speed__descriptor;
extern const ProtobufCMessageDescriptor scm_buttons__descriptor;
extern const ProtobufCMessageDescriptor seatbelt_status__descriptor;
extern const ProtobufCMessageDescriptor car_speed__descriptor;
extern const ProtobufCMessageDescriptor scm_feedback__descriptor;
extern const ProtobufCMessageDescriptor stalk_status__descriptor;
extern const ProtobufCMessageDescriptor stalk_status2__descriptor;
extern const ProtobufCMessageDescriptor doors_status__descriptor;
extern const ProtobufCMessageDescriptor odometer__descriptor;
extern const ProtobufCMessageDescriptor gearbox_cvt__descriptor;
extern const ProtobufCMessageDescriptor hud_setting__descriptor;
extern const ProtobufCMessageDescriptor cruise_data__descriptor;
extern const ProtobufCMessageDescriptor engine_data3__descriptor;
extern const ProtobufCMessageDescriptor drive_modes__descriptor;
extern const ProtobufCMessageDescriptor gearbox__descriptor;
extern const ProtobufCMessageDescriptor pcm__data__descriptor;
extern const ProtobufCMessageDescriptor vsa__data__descriptor;
extern const ProtobufCMessageDescriptor eps__data__descriptor;
extern const ProtobufCMessageDescriptor other__data__descriptor;
extern const ProtobufCMessageDescriptor all__data__descriptor;
extern const ProtobufCMessageDescriptor car_status__descriptor;
extern const ProtobufCMessageDescriptor vehicle_data_batch__descriptor;
extern const ProtobufCMessageDescriptor can_data__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_honda_5fdata_2eproto__INCLUDED */
